In [2]:
!pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2025.11.12)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 3.9 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [11]:
import pandas as pd

df = pd.read_csv('/content/Cleaned_Youtube.csv')
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,title_length,tag_count,category_name
0,2kyS6SvSYSE,NaN,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13 17:13:01+00:00,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,US,34.0,1.0,People & Blogs
1,1ZAPwfrtAFY,NaN,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13 07:30:00+00:00,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",US,62.0,4.0,Entertainment
2,5qpjK5DgCt4,NaN,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO â¶ \n\nSUBSCRIBE âº ...,US,53.0,23.0,Comedy
3,puqaWrEC7tY,NaN,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13 11:00:04+00:00,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...,US,32.0,27.0,Entertainment
4,d380meD0W0M,NaN,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,US,24.0,14.0,Entertainment

In [12]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

In [13]:
df['title_sentiment'] = df['title'].astype(str).apply(
    lambda x: sia.polarity_scores(x)['compound']
)

In [14]:
df[['title', 'title_sentiment']].head()

                                               title  title_sentiment
0                 WE WANT TO TALK ABOUT OUR MARRIAGE           0.0772
1  The Trump Presidency: Last Week Tonight with J...           0.0000
2  Racist Superman | Rudy Mancuso, King Bach & Le...          -0.6124
3                   Nickelback Lyrics: Real or Fake?          -0.4767
4                           I Dare You: GOING BALD!?           0.0000

In [15]:
def label_sent(score):
    if score >= 0.05:
        return 'Positive'
    elif score <= -0.05:
        return 'Negative'
    else:
        return 'Neutral'

df['sentiment_label'] = df['title_sentiment'].apply(label_sent)

In [16]:
df[['title', 'title_sentiment', 'sentiment_label']].head()

,title,title_sentiment,sentiment_label
0,WE WANT TO TALK ABOUT OUR MARRIAGE,0.0772,Positive
1,The Trump Presidency: Last Week Tonight with J...,0.0000,Neutral
2,"Racist Superman | Rudy Mancuso, King Bach & Le...",-0.6124,Negative
3,Nickelback Lyrics: Real or Fake?,-0.4767,Negative
4,I Dare You: GOING BALD!?,0.0000,Neutral

In [18]:
df.to_csv('/content/Cleaned_Youtube_With_Sentiment.csv', index=False)

In [22]:
import os
os.listdir('/content/')

['.config',
 'Cleaned_Youtube.csv',
 'cleaned_sql_ready.csv',
 'Cleaned_Youtube_With_Sentiment.csv',
 'sample_data']

In [23]:
import csv
df.to_csv('cleaned_sql_ready.csv', index=False, encoding='utf-8', quoting=csv.QUOTE_ALL)

In [24]:
from google.colab import files
files.download('cleaned_sql_ready.csv')